In [12]:
import pandas as pd

In [13]:
df = pd.read_excel(r'C:/Users/carla/Desktop/SSMS_Projects/resources/Customer Call List.xlsx')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [14]:
#IMPORTANT: Before assigning 'df =' in front of any changes, review the output first to avoid saving undesired alterations

In [15]:
#Delete redundant column
df = df.drop(columns = 'Not_Useful_Column')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [16]:
#Remove duplicates
df = df.drop_duplicates()
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [17]:
#Strip to remove undesired symbols on 'Last_Name' column
#Note: When cleaning the 'Last_Name' column using df['Last_Name'].str.strip("..._/ "), remember to assign the cleaned values only to that column using df['Last_Name'] =. Failing to do so might inadvertently apply these changes to the entire table, affecting other columns unintentionally
df.loc[:, 'Last_Name'] = df['Last_Name'].str.strip("..._/ ")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [56]:
#Standarize 'Phone_Number'
df['Phone_Number'] = df['Phone_Number'].str.replace('[^a-zA-Z0-9]', '')

In [61]:
df['Phone_Number'] = df['Phone_Number'].str.replace('nan--', '')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,1236439775,93 West Main Street,No,Yes
2,1003,Walter,White,,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,3047622467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,,1209 South Street,No,No
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,1235432345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,8766783469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,No
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,,N/a,N/a,Yes
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N

In [71]:
#Split Address info
#Split address into 3 different columns
address_split = df['Address'].str.split(',', n=2, expand=True)

#rename columns
address_split.columns = ['Street_Address', 'City', 'Postal_Code']

#Using .loc to asign new values to the columns
df.loc[:, ['Street_Address', 'City', 'Postal_Code']] = address_split
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Name,City,Postal Code,Street_Address,Postal_Code
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,None,123 Shire Lane,None
1,1002,Abed,Nadir,1236439775,93 West Main Street,No,Yes,93 West Main Street,None,None,93 West Main Street,None
2,1003,Walter,White,,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None,298 Drugs Driveway,None
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,Pennsylvania,18503,980 Paper Avenue,18503
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,No,123 Dragons Road,None,None,123 Dragons Road,None
5,1006,Ron,Swanson,3047622467,768 City Parkway,Yes,Yes,768 City Parkway,None,None,768 City Parkway,None
6,1007,Jeff,Winger,,1209 South Street,No,No,1209 South Street,None,None,1209 South Street,None
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,No,98 Clue Drive,None,None,98 Clue Drive,None
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,123 Middle Earth,None,None,123 Middle Earth,None
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Yes,No,25th Main Street,New York,None,25th Main Street,None
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire,None,612 Shire Lane,None
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None,2394 Hogwarts Avenue,None
12,1013,Don,Draper,1235432345,2039 Main Street,Yes,N,2039 Main Street,None,None,2039 Main Street,None
13,1014,Leslie,Knope,8766783469,343 City Parkway,Yes,No,343 City Parkway,None,None,343 City Parkway,None
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,No,214 HR Avenue,None,None,214 HR Avenue,None
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,None,None,2395 Hogwarts Avenue,None
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,None,121 Paper Avenue,None
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,3498 Super Lane,None,None,3498 Super Lane,None
18,1019,Creed,Braton,,N/a,N/a,Yes,N/a,None,None,N/a,None
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,None,910 Tatooine Road,None

In [80]:
#Standarizing 'Paying Customer' column
df['Paying Customer'] = df['Paying Customer'].str.replace('Yes', 'Y')
df['Paying Customer'] = df['Paying Customer'].str.replace('Y', 'Yes')

In [85]:
df['Paying Customer'] = df['Paying Customer'].str.replace('No', 'N')
df['Paying Customer'] = df['Paying Customer'].str.replace('N', 'No')

In [91]:
df = df.replace('No/a', '')
df = df.fillna('')

In [95]:
#Standarizing 'Do_Not_Contact'
df['Do_Not_Contact'] = df['Do_Not_Contact'].str.replace('Yes', 'Y')
df['Do_Not_Contact'] = df['Do_Not_Contact'].str.replace('Y', 'Yes')

In [98]:
df['Do_Not_Contact'] = df['Do_Not_Contact'].str.replace('No', 'N')
df['Do_Not_Contact'] = df['Do_Not_Contact'].str.replace('N', 'No')

In [92]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,City,Postal Code,Street_Address,Postal_Code
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,No,Shire,,123 Shire Lane,
1,1002,Abed,Nadir,1236439775,93 West Main Street,No,Yes,,,93 West Main Street,
2,1003,Walter,White,,298 Drugs Driveway,No,,,,298 Drugs Driveway,
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,Pennsylvania,18503,980 Paper Avenue,18503
4,1005,Jon,Snow,8766783469,123 Dragons Road,Yes,No,,,123 Dragons Road,
5,1006,Ron,Swanson,3047622467,768 City Parkway,Yes,Yes,,,768 City Parkway,
6,1007,Jeff,Winger,,1209 South Street,No,No,,,1209 South Street,
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,No,No,,,98 Clue Drive,
8,1009,Gandalf,,,123 Middle Earth,Yes,,,,123 Middle Earth,
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Yes,No,New York,,25th Main Street,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,Shire,,612 Shire Lane,
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Yes,,,,2394 Hogwarts Avenue,
12,1013,Don,Draper,1235432345,2039 Main Street,Yes,N,,,2039 Main Street,
13,1014,Leslie,Knope,8766783469,343 City Parkway,Yes,No,,,343 City Parkway,
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,No,No,,,214 HR Avenue,
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,No,N,,,2395 Hogwarts Avenue,
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,No,Pennsylvania,,121 Paper Avenue,
17,1018,Clark,Kent,,3498 Super Lane,Yes,,,,3498 Super Lane,
18,1019,Creed,Braton,,N/a,,Yes,,,N/a,
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N,Tatooine,,910 Tatooine Road,

In [102]:
#We now want to drop all the rows from people who DO NOT want to be contacted
for x in df.index:
    if df.loc[x, 'Do_Not_Contact'] == 'Yes':
        df.drop(x, inplace = True)
df

In [104]:
#Do the same thing for blank Phone_Numbers
for x in df.index:
    if df.loc[x, 'Phone_Number'] == '':
        df.drop(x, inplace = True)
df

In [108]:
#Reorganize index
df.reset_index()
df = df.reset_index(drop=True)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,City,Postal Code,Street_Address,Postal_Code
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,No,Shire,,123 Shire Lane,
1,1005,Jon,Snow,8766783469,123 Dragons Road,Yes,No,,,123 Dragons Road,
2,1008,Sherlock,Holmes,8766783469,98 Clue Drive,No,No,,,98 Clue Drive,
3,1010,Peter,Parker,1235455421,"25th Main Street, New York",Yes,No,New York,,25th Main Street,
4,1013,Don,Draper,1235432345,2039 Main Street,Yes,No,,,2039 Main Street,
5,1014,Leslie,Knope,8766783469,343 City Parkway,Yes,No,,,343 City Parkway,
6,1015,Toby,Flenderson,3047622467,214 HR Avenue,No,No,,,214 HR Avenue,
7,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,No,No,,,2395 Hogwarts Avenue,
8,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,No,Pennsylvania,,121 Paper Avenue,
9,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,No,Tatooine,,910 Tatooine Road,

In [109]:
#Final Product
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,City,Postal Code,Street_Address,Postal_Code
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,No,Shire,,123 Shire Lane,
1,1005,Jon,Snow,8766783469,123 Dragons Road,Yes,No,,,123 Dragons Road,
2,1008,Sherlock,Holmes,8766783469,98 Clue Drive,No,No,,,98 Clue Drive,
3,1010,Peter,Parker,1235455421,"25th Main Street, New York",Yes,No,New York,,25th Main Street,
4,1013,Don,Draper,1235432345,2039 Main Street,Yes,No,,,2039 Main Street,
5,1014,Leslie,Knope,8766783469,343 City Parkway,Yes,No,,,343 City Parkway,
6,1015,Toby,Flenderson,3047622467,214 HR Avenue,No,No,,,214 HR Avenue,
7,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,No,No,,,2395 Hogwarts Avenue,
8,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,No,Pennsylvania,,121 Paper Avenue,
9,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,No,Tatooine,,910 Tatooine Road,